[project]
name = "fruit-cli"
version = "0.1.0"
description = "A CLI tool to generate random fruits"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
fruit = "main:main"
